blank_issues_enabled: false
contact_links:
  - name: 🤔 Long question or idea?
    url: https://github.com/react-grid-layout/react-grid-layout/discussions
    about: Ask long-form questions and discuss ideas.
  - name: 👥 Community Code Examples for `react-grid-layout`
    url: https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=react-grid-layout&refinementList%5Btemplate%5D%5B0%5D=create-react-app&refinementList%5Btemplate%5D%5B1%5D=create-react-app-typescript&page=1&configure%5BhitsPerPage%5D=12
    about: See `react-grid-layout` examples created by our community of users
