/**
 * Regression tests for #2110 — data-grid seeding on breakpoint growth.
 *
 * The bug: when an item is added at a small breakpoint (e.g. md) via a child's
 * `data-grid` prop, then the container widens so a larger breakpoint (e.g. lg)
 * layout is generated by cloning the md layout, the generated lg layout keeps
 * the md-stored w/h. The item shrinks even though its child still declares a
 * wider `data-grid` width.
 *
 * These tests exercise the component path (`ResponsiveGridLayout`), not just
 * `findOrGenerateResponsiveLayout` in isolation.
 */
import * as React from "react";
import { render, act } from "@testing-library/react";
import { ResponsiveGridLayout } from "../../src/react/components/ResponsiveGridLayout";
import type { Layout, ResponsiveLayouts } from "../../src/core/types";

const BREAKPOINTS = { lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 };
const COLS = { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 };

describe("#2110 data-grid seeding on breakpoint growth", () => {
  it("re-seeds w/h from data-grid when the layout grows to a larger breakpoint", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (layout: Layout) => {
      layoutChanges.push(layout);
    };

    // Start at md. The item "widget" is authored with w:6 in its data-grid.
    const { rerender } = render(
      <ResponsiveGridLayout
        width={1000}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        onLayoutChange={onLayoutChange}
      >
        <div key="widget" data-grid={{ x: 3, y: 0, w: 6, h: 1 }}>
          widget
        </div>
      </ResponsiveGridLayout>
    );

    // Grow to lg. lg is not authored, so it is generated by cloning the md
    // layout. The child still declares w:6, so the item must not shrink to
    // the md-stored w.
    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1300}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          onLayoutChange={onLayoutChange}
        >
          <div key="widget" data-grid={{ x: 3, y: 0, w: 6, h: 1 }}>
            widget
          </div>
        </ResponsiveGridLayout>
      );
    });

    const lastLayout = layoutChanges[layoutChanges.length - 1];
    expect(lastLayout).toBeDefined();
    const widget = lastLayout!.find(item => item.i === "widget");
    expect(widget).toBeDefined();
    // The item must keep its authored data-grid width, never the md-cloned one.
    expect(widget!.w).toBe(6);
    expect(widget!.h).toBe(1);
  });

  it("preserves the stored x/y when re-seeding size from data-grid", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (layout: Layout) => {
      layoutChanges.push(layout);
    };

    // Start at md. The item was dragged to x:5 in the md layout, but its
    // data-grid still declares x:3.
    const { rerender } = render(
      <ResponsiveGridLayout
        width={1000}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        layouts={{
          // static so the vertical compactor leaves the stored y alone.
          md: [{ i: "widget", x: 5, y: 2, w: 3, h: 1, static: true }]
        }}
        onLayoutChange={onLayoutChange}
      >
        <div key="widget" data-grid={{ x: 3, y: 0, w: 6, h: 1 }}>
          widget
        </div>
      </ResponsiveGridLayout>
    );

    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1300}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          layouts={{
            md: [{ i: "widget", x: 5, y: 2, w: 3, h: 1, static: true }]
          }}
          onLayoutChange={onLayoutChange}
        >
          <div key="widget" data-grid={{ x: 3, y: 0, w: 6, h: 1 }}>
            widget
          </div>
        </ResponsiveGridLayout>
      );
    });

    const lastLayout = layoutChanges[layoutChanges.length - 1];
    expect(lastLayout).toBeDefined();
    const widget = lastLayout!.find(item => item.i === "widget");
    expect(widget).toBeDefined();
    // Size is re-seeded from data-grid (never shrinks)...
    expect(widget!.w).toBe(6);
    expect(widget!.h).toBe(1);
    // ...but the user's drag position is preserved from the stored layout.
    expect(widget!.x).toBe(5);
    expect(widget!.y).toBe(2);
  });

  it("does not clobber layout-driven sizes for children without data-grid", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (layout: Layout) => {
      layoutChanges.push(layout);
    };

    const layouts: ResponsiveLayouts<string> = {
      md: [{ i: "widget", x: 0, y: 0, w: 3, h: 2 }]
    };

    const { rerender } = render(
      <ResponsiveGridLayout
        width={1000}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        layouts={layouts}
        onLayoutChange={onLayoutChange}
      >
        <div key="widget">widget</div>
      </ResponsiveGridLayout>
    );

    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1300}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          layouts={layouts}
          onLayoutChange={onLayoutChange}
        >
          <div key="widget">widget</div>
        </ResponsiveGridLayout>
      );
    });

    const lastLayout = layoutChanges[layoutChanges.length - 1];
    expect(lastLayout).toBeDefined();
    const widget = lastLayout!.find(item => item.i === "widget");
    expect(widget).toBeDefined();
    // No data-grid on the child, so the generated lg layout keeps the md size.
    expect(widget!.w).toBe(3);
    expect(widget!.h).toBe(2);
  });
});
