/**
 * Regression tests for #1744 — gap collapse through the component path.
 *
 * The bug: when a breakpoint layout is generated from a source layout that has
 * gaps (items separated vertically instead of stacked), the generated layout
 * keeps the gaps, so items overflow the container instead of compacting up.
 *
 * The pure-function test (`responsive-generation-test.ts`) covers
 * `findOrGenerateResponsiveLayout` in isolation. These tests exercise the
 * `ResponsiveGridLayout` component path — the width-change effect that calls
 * the generator, the children re-sync, and the stored/re-used layout — because
 * the gap could survive any of those hops even if the pure function is correct.
 */
import * as React from "react";
import { render, act } from "@testing-library/react";
import { ResponsiveGridLayout } from "../../src/react/components/ResponsiveGridLayout";
import type { Layout, ResponsiveLayouts } from "../../src/core/types";

const BREAKPOINTS = { lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 };
const COLS = { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 };

describe("#1744 gap collapse on breakpoint generation (component path)", () => {
  it("collapses a mid-grid gap when a smaller breakpoint layout is generated", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (
      layout: Layout,
      _layouts: ResponsiveLayouts<string>
    ) => {
      layoutChanges.push(layout);
    };

    // lg layout with a gap at y=1 (item A at y=0, item C at y=2).
    const layouts: ResponsiveLayouts<string> = {
      lg: [
        { i: "A", x: 0, y: 0, w: 12, h: 1 },
        { i: "C", x: 0, y: 2, w: 12, h: 1 }
      ]
    };

    const { rerender } = render(
      <ResponsiveGridLayout
        width={1300}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        layouts={layouts}
        onLayoutChange={onLayoutChange}
      >
        <div key="A">A</div>
        <div key="C">C</div>
      </ResponsiveGridLayout>
    );

    // Shrink to md. md is not authored, so it is generated by cloning the lg
    // layout and compacting. The gap at y=1 must collapse.
    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1000}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          layouts={layouts}
          onLayoutChange={onLayoutChange}
        >
          <div key="A">A</div>
          <div key="C">C</div>
        </ResponsiveGridLayout>
      );
    });

    const mdLayout = layoutChanges[layoutChanges.length - 1];
    expect(mdLayout).toBeDefined();
    const itemC = mdLayout!.find(item => item.i === "C");
    expect(itemC).toBeDefined();
    // C must have been pulled up into the gap at y=1.
    expect(itemC!.y).toBe(1);
    // Sanity: the width is clamped to md's 10 cols, proving this is the
    // generated md layout, not a stale lg one.
    const itemA = mdLayout!.find(item => item.i === "A");
    expect(itemA).toBeDefined();
    expect(itemA!.w).toBe(10);
  });

  it("collapses a gap in an already-stored target breakpoint layout when re-used", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (
      layout: Layout,
      _layouts: ResponsiveLayouts<string>
    ) => {
      layoutChanges.push(layout);
    };

    // Both md and lg are authored. The stored md layout has a mid-grid gap
    // (C at y=2). When the container shrinks to md, the layout is *re-used*
    // (not generated), so findOrGenerateResponsiveLayout returns it as-is.
    // The children re-sync must still compact the gap.
    const layouts: ResponsiveLayouts<string> = {
      lg: [
        { i: "A", x: 0, y: 0, w: 12, h: 1 },
        { i: "C", x: 0, y: 1, w: 12, h: 1 }
      ],
      md: [
        { i: "A", x: 0, y: 0, w: 10, h: 1 },
        { i: "C", x: 0, y: 2, w: 10, h: 1 }
      ]
    };

    const { rerender } = render(
      <ResponsiveGridLayout
        width={1300}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        layouts={layouts}
        onLayoutChange={onLayoutChange}
      >
        <div key="A">A</div>
        <div key="C">C</div>
      </ResponsiveGridLayout>
    );

    // Shrink to md — the stored md layout is re-used.
    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1000}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          layouts={layouts}
          onLayoutChange={onLayoutChange}
        >
          <div key="A">A</div>
          <div key="C">C</div>
        </ResponsiveGridLayout>
      );
    });

    const mdLayout = layoutChanges[layoutChanges.length - 1];
    expect(mdLayout).toBeDefined();
    const itemC = mdLayout!.find(item => item.i === "C");
    expect(itemC).toBeDefined();
    // The stored gap at y=1 must still collapse via the children re-sync.
    expect(itemC!.y).toBe(1);
    // The md width clamp proves this is the generated/re-used md layout, not a
    // stale lg one (lg w=12 → md w=10).
    const itemA = mdLayout!.find(item => item.i === "A");
    expect(itemA).toBeDefined();
    expect(itemA!.w).toBe(10);
  });

  it("collapses the gap even when the source layout is re-passed with gaps", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (
      layout: Layout,
      _layouts: ResponsiveLayouts<string>
    ) => {
      layoutChanges.push(layout);
    };

    // A fresh object reference with the same gap content is passed on every
    // render, forcing the derived-layout path in the component.
    const makeLayouts = (): ResponsiveLayouts<string> => ({
      lg: [
        { i: "A", x: 0, y: 0, w: 12, h: 1 },
        { i: "C", x: 0, y: 2, w: 12, h: 1 }
      ]
    });

    const { rerender } = render(
      <ResponsiveGridLayout
        width={1300}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        layouts={makeLayouts()}
        onLayoutChange={onLayoutChange}
      >
        <div key="A">A</div>
        <div key="C">C</div>
      </ResponsiveGridLayout>
    );

    // Re-pass the gap layout (new reference) then shrink, in one act.
    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1000}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          layouts={makeLayouts()}
          onLayoutChange={onLayoutChange}
        >
          <div key="A">A</div>
          <div key="C">C</div>
        </ResponsiveGridLayout>
      );
    });

    const mdLayout = layoutChanges[layoutChanges.length - 1];
    expect(mdLayout).toBeDefined();
    const itemC = mdLayout!.find(item => item.i === "C");
    expect(itemC).toBeDefined();
    expect(itemC!.y).toBe(1);
    // Width clamp proves this is the generated md layout, not a stale lg one.
    const itemA = mdLayout!.find(item => item.i === "A");
    expect(itemA).toBeDefined();
    expect(itemA!.w).toBe(10);
  });

  it("does not re-introduce the gap when the generated layout is re-seeded from data-grid children", () => {
    const layoutChanges: Layout[] = [];
    const onLayoutChange = (
      layout: Layout,
      _layouts: ResponsiveLayouts<string>
    ) => {
      layoutChanges.push(layout);
    };

    // Children author data-grid y positions that leave a gap at y=1. When md
    // is generated and re-seeded from these data-grid props, the authored gap
    // must not be restored — stored/generated x/y positions win for layout,
    // and compaction must keep C pulled up.
    const layouts: ResponsiveLayouts<string> = {
      lg: [
        { i: "A", x: 0, y: 0, w: 12, h: 1 },
        { i: "C", x: 0, y: 2, w: 12, h: 1 }
      ]
    };

    const { rerender } = render(
      <ResponsiveGridLayout
        width={1300}
        breakpoints={BREAKPOINTS}
        cols={COLS}
        layouts={layouts}
        onLayoutChange={onLayoutChange}
      >
        <div key="A" data-grid={{ x: 0, y: 0, w: 12, h: 1 }}>
          A
        </div>
        <div key="C" data-grid={{ x: 0, y: 2, w: 12, h: 1 }}>
          C
        </div>
      </ResponsiveGridLayout>
    );

    act(() => {
      rerender(
        <ResponsiveGridLayout
          width={1000}
          breakpoints={BREAKPOINTS}
          cols={COLS}
          layouts={layouts}
          onLayoutChange={onLayoutChange}
        >
          <div key="A" data-grid={{ x: 0, y: 0, w: 12, h: 1 }}>
            A
          </div>
          <div key="C" data-grid={{ x: 0, y: 2, w: 12, h: 1 }}>
            C
          </div>
        </ResponsiveGridLayout>
      );
    });

    const mdLayout = layoutChanges[layoutChanges.length - 1];
    expect(mdLayout).toBeDefined();
    const itemC = mdLayout!.find(item => item.i === "C");
    expect(itemC).toBeDefined();
    expect(itemC!.y).toBe(1);
    // Width clamp proves this is the generated md layout, not a stale lg one.
    const itemA = mdLayout!.find(item => item.i === "A");
    expect(itemA).toBeDefined();
    expect(itemA!.w).toBe(10);
  });
});
