---
name: Pull request labeler
on:
  - pull_request_target
jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
